apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloapp
spec:
  selector:
    matchLabels:
      app: helloapp
  template:
    metadata:
      labels:
        app: helloapp
    spec:
      containers:
      - name: helloapp
        image: gcr.io/google-samples/hello-app@sha256:8e836aef1ec98bf41189a7b14fa94434e97244fa9106461bef02d0696da20af8
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
