apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloapp-deploy
  labels:
    app: helloapp
    tier: web
spec:
  selector:
    matchLabels:
      app: helloapp
  template:
    metadata:
      labels:
        app: helloapp
    spec:
      containers:
      - name: helloapp
        image: gcr.io/google-samples/hello-app@sha256:8e836aef1ec98bf41189a7b14fa94434e97244fa9106461bef02d0696da20af8
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: helloapp-service
spec:
  selector:
    app: helloapp
  ports:
  - port: 8080
    targetPort: 8080
  type: NodePort